#name: gitlab

services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:18.11.5-ce.0'
    restart: "no"
    #hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.kaban77.com'
        registry_external_url 'https://gitlab.kaban77.com:5050'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['listen_port'] = 443
        nginx['listen_https'] = true
    ports:
      - '8089:80'
      - '2224:22'
      - '443:443'
      - '5050:5050'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      gitlab-network:
        aliases:
          - gitlab.kaban77.com
    shm_size: '1024m'
  # RUNNER
  gitlab-runner1:
    image: gitlab/gitlab-runner:v18.11.3
    restart: "no"
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    depends_on:
      - gitlab-web
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
       - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network
