#name: gitlab

services:
  gitlab-web:
    image: 'gitlab/gitlab-ce:17.9.0-ce.0'
    restart: "no"
    hostname: 'gitlab.kaban77.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.kaban77.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '192.168.31.204:8089:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '1024m'
  # RUNNER
  gitlab-runner1:
    image: gitlab/gitlab-runner:v17.9.0
    restart: "no"
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    depends_on:
      - gitlab-web
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
       - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network
